[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "Unlicense",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "BSD-4-Clause",
    "ISC",
    "Zlib",
    "OpenSSL",
    "CC0-1.0",
    "MIT-0",
    "BSL-1.0",
    "Apache-2.0 WITH LLVM-exception",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
