[alias]
lint = "clippy --workspace --all-targets --all-features -D warnings"
test-all = "test --workspace --all-features"
nextest-ci = "nextest run --workspace --all-features --profile ci --failure-output=final"
cov = "llvm-cov --workspace --ignore-filename-regex '(.cargo|.git|/tests?/)' --html"
udeps = "udeps --workspace"

[build]
rustflags = ["-Dwarnings"]

[term]
color = "auto"
